#!/bin/sh

# Set these paths appropriately

BIN=/tmp/HS/Tagger/bin
CMD=/tmp/HS/Tagger/cmd
LIB=/tmp/HS/Tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/finnish-abbreviations-utf8
PARFILE=${LIB}/finnish-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE

