#!/bin/sh

# Set these paths appropriately

BIN=./bin
CMD=./cmd
LIB=./lib

OPTIONS="-quiet"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

#$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
